variables:
  GIT_SUBMODULE_STRATEGY: none
  GIT_CLEAN_FLAGS: none
  GIT_STRATEGY: none

stages:
  - deploy

pull-site:
  when: manual
  stage: deploy
  only:    
    - master
    - dev
  script:
    - cd /var/vega.fcyb.mirea.ru/accel/
    - git fetch
    - git checkout ${CI_COMMIT_REF_NAME}
    - git pull origin ${CI_COMMIT_REF_NAME}
    - git submodule init || true
    - git submodule update --recursive || true
    - git reset --hard ${CI_COMMIT_SHORT_SHA}
  tags:
    - vega-site


