version: '3.9'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network
    extra_hosts:
      - "vector:127.0.0.1"
    command: sh -c "npm install && npx tsc && node ./dist/index.js"
  
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    user: root
    volumes:
      - .:/var/www/html
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      HOST_DIR: "/var/www/docker/accel" # для работы тестирования, менять на разположения откуда запускается докер  
    networks:
      - app-network


  nginx:
    image: nginx:1.24.0
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./for_docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network


  psql:
    build:
      context: .
      dockerfile: Dockerfile.psql
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge