# Используем официальный образ Node.js
FROM node:18

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем весь код приложения в контейнер
COPY . .

RUN npx tsc

# Устанавливаем порт
EXPOSE 3000

# Команда для запуска приложения
CMD ["node", "./dist/index.js"]
