version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - .:/var/www/html
    networks:
      - app-network


  nginx:
    image: nginx:1.24.0
    # build:
    #   context: .
    #   dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network


  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network
    extra_hosts:
      - "vector:127.0.0.1"

  psql:
    build:
      context: .
      dockerfile: Dockerfile.psql
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge