# Используем официальный образ Nginx
FROM nginx:1.24.0

# Копируем конфигурацию Nginx
# COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

# COPY . /var/www/html

# Копируем файл конфигурации fastcgi-php.conf
# COPY ./nginx/snippets/fastcgi-php.conf /etc/nginx/snippets/fastcgi-php.conf


# Expose порта для Nginx
EXPOSE 80
