version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - .:/var/www/html


  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
