GRANT ALL PRIVILEGES ON DATABASE accelerator TO accelerator;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO accelerator;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO accelerator;

GRANT ALL PRIVILEGES ON SCHEMA ax TO accelerator;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ax TO accelerator;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA ax TO accelerator;