#!/usr/bin/env sh

git fetch origin

# https://github.com/commitizen-tools/commitizen/blob/master/docs/commands/bump.md
# Список ошибок Commitizen: https://commitizen-tools.github.io/commitizen/exit_codes/
pipenv run cz --no-raise 3,21 bump --changelog --retry